# Generated by Django 3.2.23 on 2023-12-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='salt',
            field=models.CharField(max_length=100),
        ),
    ]
